### ISSUE TITLE
CheckoutSettings.getProviderMode()' on a null object reference

### ISSUE THREAD

**Issue by qamarkhanInnovo** [checkout/frames-android#141] opened 2022-10-31 07:44 UTC
Hello checkout team.
we are getting this error on some devices also we provide all the necessary details while initialise the sdk.

```
binding.checkoutCardForm.set3DSListener(m3DSecureListener)
            .setEnvironment(if (BuildConfig.DEBUG) Environment.SANDBOX else Environment.LIVE)
            .setKey(if (BuildConfig.DEBUG) BuildConfig.PAYMENT_GATEWAY_ENVIRONMENT_SANDBOX else BuildConfig.PAYMENT_GATEWAY_ENVIRONMENT_LIVE)
```

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'com.oppwa.mobile.connect.provider.Connect$ProviderMode com.oppwa.mobile.connect.checkout.meta.CheckoutSettings.getProviderMode()' on a null object reference.
com.oppwa.mobile.connect.checkout.dialog.BaseServiceActivity$1.onServiceConnected (Unknown Source:55)

please reply us ASAP our app is already in production mode.

**Comment by maxim-nosov-cko** [comment] 2022-10-31 08:45
Hi @qamarkhanInnovo.
From provided information, it's hard to say what the issue is and how it's related to frames-android SDK.
Could you please provide a full stacktrace?

**Comment by qamarkhanInnovo** [comment] 2022-10-31 12:47
Hello @maxim-nosov-cko.
This issue report from firebase crashlytics. this is the full stracktrace which i got from there.
After this i go to the checkout sdk implementation and verify my implementation according to provided documentation, its all okay. 

--> com.oppwa.mobile.connect.checkout.meta.CheckoutSettings.getProviderMode()' on a null object reference.
(then i go to checkout setting class and check what is provided mode ? you could check below i provided code). 

```
public class CheckoutSettings implements Parcelable {
    @NonNull
    private String a;
    private String b;
    @NonNull
    private ProviderMode c;
```
this is provider mode enum class
```
public static enum ProviderMode {
        LIVE,
        TEST;

        private ProviderMode() {
        }
    }
```

if you check my above comment where i send mode like `.setEnvironment(if (BuildConfig.DEBUG) Environment.SANDBOX else Environment.LIVE)` live or sandbox. 
i dont know why this issue comes on some devices and other are okay. 
i used this sdk` implementation 'com.github.checkout:frames-android:3.0.1'`

**Comment by patrick-hoban-cko** [comment] 2023-05-25 10:23
Hi @qamarkhanInnovo, seeing as this issue is quite old, I'd recommend upgrading to the latest version of our Android SDK (v4.0.2), to see if that resolves it.

I will close this ticket for now, but if you continue to face the issue after using the newest version, please do raise another ticket. 

Best,

Patrick

**Closed by patrick-hoban-cko** 2023-05-25 10:23 UTC
