### ISSUE TITLE
Issue with PaymentForm.injectCardHolderName

### ISSUE THREAD

**Issue by ValeriiMamo** [checkout/frames-android#54] opened 2021-03-30 13:56 UTC
**Describe the bug**
Specifying PaymentForm.injectCardHolderName doesn't work.

**To Reproduce**

First scenarion:
1. Initialize form by the following:
val paymentForm = checkoutCard
            .setEnvironment(if (BuildTypes.isRelease) LIVE else SANDBOX)
            .setKey(getString(R.string.checkout_sdk_key))
            .setFormListener(formListener)
            .setPayButtonText(getString(R.string.wallet_enter_card_details_save_label))
            .injectCardHolderName(user.fullName)

Second scenarion:
1. Initialize form by the following:
val paymentForm = checkoutCard
            .setEnvironment(if (BuildTypes.isRelease) LIVE else SANDBOX)
            .setKey(getString(R.string.checkout_sdk_key))
            .setFormListener(formListener)
            .setPayButtonText(getString(R.string.wallet_enter_card_details_save_label))
2. Set card holder's name: paymentForm.injectCardHolderName(userName)

**Expected behavior**
Card's holder names is shown on UI.

**Screenshots**
![telegram-cloud-photo-size-2-5411114840103171168-y](https://user-images.githubusercontent.com/63181542/113000781-d1fc2d80-9178-11eb-8467-09f36dfed202.jpg)

**Smartphone (please complete the following information):**
 - Device: Pixel 2
  - OS: [e.g. Android 11.0]

**Comment by shavinda-rabichandran-cko** [comment] 2021-04-12 15:47
This issue could not be reproduced. However, functionality related to injecting data has been refactored to improve stability in #55  , #56 , #57 & #58 . 

This issue will be closed, if the problem is still present in version 3.0.1 this can be reopened for further investigation.

**Comment by shavinda-rabichandran-cko** [comment] 2021-04-19 08:56
Closing issue due to no feedback.
The issue should be fixed with the latest release 3.0.1

**Closed by shavinda-rabichandran-cko** 2021-04-19 08:56 UTC
