### ISSUE TITLE
When using 3d secure the listener doesn't work if success or not

### ISSUE THREAD

**Issue by amerelsayedn1** [checkout/frames-android#113] opened 2022-08-17 21:33 UTC
However using this in my code 

PaymentForm.On3DSFinished m3DSecureListener =
  new PaymentForm.On3DSFinished() {
    @Override
    public void onSuccess(String token) {
      // success
    }
    @Override
    public void onError(String errorMessage) {
      // fail
    }
  };

success or fail doesn't work after redirect to success or fail webview after entering otp code so please help

**Comment by maxim-nosov-cko** [comment] 2022-08-18 09:15
Hi @amerelsayedn1

Was On3DSFinished listener set to PaymentForm?
Example: https://github.com/checkout/frames-android/blob/master/app/src/main/java/checkout/checkout_android/DemoActivity.java#:~:text=.set3DSListener(m3DSecureListener)

**Comment by amerelsayedn1** [comment] 2022-08-18 09:35
That what i do right now but it's no list to success of 3ds ?? 
did you know why this happen ?

**Comment by maxim-nosov-cko** [comment] 2022-08-18 10:41
Do you receive any errors?
Are success and failure url the same for both payment request and 3DS handling?

Could you please check out [demo application](https://github.com/checkout/frames-android/tree/master/app)?

**Comment by juchampagne** [comment] 2022-09-23 08:54
Hey @maxim-nosov-cko 

We are experiencing a similar issue, the success or failure urls are never passed to the onPageFinished, instead it got one of the redirect url that happen after.

For what I can see between iOS and Android, is that iOS is getting all the redirect urls in the handleDismiss method.

`private func handleDismiss(redirectUrl: URL) -> Bool {

        if let successUrl = successUrl,
           urlHelper.urlsMatch(redirectUrl: redirectUrl, matchingUrl: successUrl) {
            // success url, dismissing the page with the payment token

            self.dismiss(animated: true) { [urlHelper, delegate, logger] in
                let token = urlHelper.extractToken(from: redirectUrl)
                delegate?.threeDSWebViewControllerAuthenticationDidSucceed(self, token: token)
                delegate?.onSuccess3D()
                logger?.log(.threeDSChallengeComplete(success: true, tokenID: token))
            }

            return true
        } else if let failUrl = failUrl,
                  urlHelper.urlsMatch(redirectUrl: redirectUrl, matchingUrl: failUrl) {
            // fail url, dismissing the page
            self.dismiss(animated: true) { [delegate, logger] in
                delegate?.threeDSWebViewControllerAuthenticationDidFail(self)
                delegate?.onFailure3D()
                logger?.log(.threeDSChallengeComplete(success: false, tokenID: nil))
            }

            return true
        }

        return false
    }`

If I put a breakpoint in that method, I can see that it first receives the success url (/confirm_3ds), then it got a redirect to the web user dashboard (/user), but since the user is actually not logged in within the web view, I got redirected to /login.

`override fun onPageFinished(view: WebView?, url: String?) {
        super.onPageFinished(view, url)

        // Listen for when the URL changes and match it with either the success of fail url
        if (url == null) {
            m3DSecureListener.onError("Url is null")
            return
        }
        when {
            url.contains(successUrl) -> {
                sendThreedsWebViewCompleteEvent(getToken(url), true)
                m3DSecureListener.onSuccess(getToken(url))
            }
            url.contains(failUrl) -> {
                sendThreedsWebViewCompleteEvent("", false)
                m3DSecureListener.onError(getToken(url))
            }
        }
    }`

If I do the same in Android, the only redirect url it receives is the last one, /login.

If Android was receiving the first urls like on iOS, it would have worked, so why these other urls are not triggering that onPageFinished callback?

Many thanks

**Comment by maxim-nosov-cko** [comment] 2022-09-23 09:35
Hi @juchampagne,

Could I ask you to add breakpoints for both onPageStarted and onPageFinished?
And please let me know onPageStarted is invoked for all URLs or not.
If assumption of mine is correct, URL without redirections could be a fast fix on your side.

**Comment by juchampagne** [comment] 2022-09-23 09:44
@maxim-nosov-cko 

I have put breakpoints in onPageStarted, onPageCommitVisible, and onPageFinished.

They are all getting called in that order but only with that last url (/login), not the other ones.

**Comment by maxim-nosov-cko** [comment] 2022-09-23 10:00
@juchampagne

Why does `/confirm_3ds` redirect to somewhere else? What is the business logic under it?
Is it possible to use another success/failure URL without such redirection or avoid redirecting for `/confirm_3ds`?

**Comment by juchampagne** [comment] 2022-09-23 10:06
@maxim-nosov-cko 

This is part of the web logic when 3ds is done on the web.

That will probably be hard to change that side, and we might look into that if there is nothing else that could be done, but if there was a possible solution to get it to work within the android sdk, that would be a lot easier.

**Comment by maxim-nosov-cko** [comment] 2022-09-26 10:17
Hi @juchampagne,

We tried few URLs with similar redirect scenarios and the issue wasn't spotted.

To be sure that implementation is correct and the cause of the issue is a URL redirection, could you please use our [demo app](https://github.com/checkout/frames-android/tree/master/app) with your success URL?
To do it, just place your URLs to [SUCCESS_URL and FAILURE_URL](https://github.com/checkout/frames-android/blob/master/app/src/main/java/checkout/checkout_android/Constants.java).

**Comment by juchampagne** [comment] 2022-09-26 11:30
Hi @maxim-nosov-cko 

Our backend devs have changed the urls now, they are static pages without redirections, and it works, the android sdk gets only one url back and that the right one this time.

And unfortunately I can't check if that still an issue with your demo app as the urls are now without redirects.

**Comment by deepesh-vasthimal-cko** [comment] 2022-09-26 14:14
Closing this issue now, Please feel free to raise a new one if needed.

**Closed by deepesh-vasthimal-cko** 2022-09-26 14:14 UTC
