### ISSUE TITLE
Manifest Merge failed with attribute application@theme and further issue

### ISSUE THREAD

**Issue by thinhnguyen18** [checkout/frames-android#94] opened 2022-07-06 03:45 UTC
I'm getting build fail when adding your library to dependencies:

> Manifest merger failed : Attribute application@theme value=(@style/AppTheme.Blue.NoActionBar) from AndroidManifest.xml:45:9-57
	is also present at [com.github.checkout:frames-android:3.1.2] AndroidManifest.xml:12:18-49 value=(@style/AppTheme).
	Suggestion: add 'tools:replace="android:theme"' to <application> element at AndroidManifest.xml:6:5-81:19 to override.

After adding `tools:replace="android:theme"` I have another exception here:

> Duplicate key: (row=dimen, column=button_height), values: [UNDEFINED dimen button_height = 0x7f07005f, UNDEFINED dimen button_height = 0x7f07005c].

There is no `button_height` key in my `dimens` and I also try to override the `button_height` but it doesn't work.

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/50190091/177463398-6a8ca511-7f81-4105-bdbc-333ebcbf62ec.png">

**Comment by maxim-nosov-cko** [comment] 2022-07-07 11:44
Hi @thinhnguyen18.

We are not able to reproduce it.
Please take a look at our demo applications.

Also need to mention, that such an issue can appear when the same key is spotted in some other library.
Can you please check it?

What SDK, Gradle, Kotlin versions and third-party dependencies are you using?

**Comment by thinhnguyen18** [comment] 2022-07-11 08:01
Hi @maxim-nosov-cko,
Thanks for your response.
I applied Checkout demo versions (SDK, Gradle, Kotlin versions, and third-party dependencies) to our project but I still can't find the root cause.
I'm using these versions:
>  compileSdkVersion 31
buildToolsVersion "30.0.3"
Gradle
version com.android.tools.build:gradle:4.1.3
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
Kotlin version '1.5.21'

Our third-party dependencies:

> // GeeTest Captcha
    implementation(name: 'geetest_captcha_android_v1.7.1.1_20220308', ext: 'aar')
    // test
    testImplementation "junit:junit:4.12"
    testImplementation "org.mockito:mockito-core:3.12.4"
    testImplementation "org.mockito:mockito-inline:3.12.4"
    // kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    // androidx & google
    implementation 'com.google.guava:guava:27.0.1-android'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation "com.google.android.material:material:1.4.0"
    //Note: Changing appcompat version will affect our changing language feature.
    implementation "androidx.appcompat:appcompat:1.1.0"
    implementation "androidx.gridlayout:gridlayout:1.0.0"
    implementation "androidx.legacy:legacy-support-v4:1.0.0"
    implementation "androidx.recyclerview:recyclerview:1.1.0"
    implementation "androidx.emoji:emoji:1.1.0"
    implementation "androidx.emoji:emoji-appcompat:1.1.0"
    implementation "androidx.emoji:emoji-bundled:1.1.0"
    implementation "androidx.annotation:annotation:1.1.0"
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation "androidx.fragment:fragment-ktx:1.3.6"
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1'
    implementation 'androidx.biometric:biometric:1.0.1'
    // svg
    implementation 'com.caverock:androidsvg:1.4'
    // glide
    kapt "com.github.bumptech.glide:compiler:4.12.0"
    implementation "com.github.bumptech.glide:glide:4.12.0"
    annotationProcessor "com.github.bumptech.glide:compiler:4.12.0"
    // butter knife
    implementation "com.jakewharton:butterknife:10.1.0"
    annotationProcessor "com.jakewharton:butterknife-compiler:10.1.0"
    kapt "com.jakewharton:butterknife-compiler:10.1.0"
    // qrgen
    implementation "com.github.kenglxn.QRGen:android:2.5.0"
    // multidex
    implementation "androidx.multidex:multidex:2.0.1"
    // rxjava
    implementation "io.reactivex.rxjava2:rxandroid:2.0.2"
    implementation "io.reactivex.rxjava2:rxjava:2.2.0"
    implementation "com.squareup.retrofit2:adapter-rxjava2:2.9.0"
    // jsonwebtoken
    implementation "io.jsonwebtoken:jjwt:0.6.0"
    // okhttp
    implementation "com.squareup.okhttp3:okhttp:4.9.1"
    implementation "com.squareup.retrofit2:retrofit:2.9.0"
    implementation "com.squareup.retrofit2:converter-gson:2.9.0"
    implementation "com.squareup.okhttp3:logging-interceptor:4.9.1"
    // zbar
    implementation 'me.dm7.barcodescanner:zbar:1.9.13'
    // dagger
    implementation "com.google.dagger:dagger:2.22"
    annotationProcessor "com.google.dagger:dagger-compiler:2.22"
    kapt "com.google.dagger:dagger-compiler:2.22"
    // play service
    implementation "com.google.android.gms:play-services-gcm:17.0.0"
    implementation "com.google.android.gms:play-services-analytics:17.0.0"
    implementation "com.google.android.gms:play-services-vision:20.1.1"
    // firebase
    implementation 'com.google.firebase:firebase-config:20.0.4'
    implementation 'com.google.firebase:firebase-messaging:21.1.0'
    implementation 'com.google.firebase:firebase-analytics:18.0.3'
    implementation 'com.google.firebase:firebase-inappmessaging-display:19.1.5'
    implementation 'com.google.firebase:firebase-core:18.0.3'
    implementation 'com.google.firebase:firebase-firestore:22.1.2'
    implementation 'com.google.firebase:firebase-crashlytics:18.2.8'
    // lottie
    implementation 'com.airbnb.android:lottie:3.4.1'
    // leakcanary
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.7'
    // segment
    implementation 'com.segment.analytics.android:analytics:4.7.1'
    implementation "com.google.code.gson:gson:2.8.6"
    // lokalise
    implementation 'com.lokalise.android:ota-sdk:1.3.15'
    // intercom
    implementation 'io.intercom.android:intercom-sdk:10.6.0'
    //segment - intercom
    implementation 'com.segment.analytics.android.integrations:intercom:+'
    implementation ("io.github.singpass:singpass-webview-client:1.2.0")
    implementation 'com.googlecode.libphonenumber:libphonenumber:8.2.0'
    implementation 'com.segment.analytics.android.integrations:firebase:2.3.0@aar'
    implementation "com.sumsub.sns:idensic-mobile-sdk:1.19.5"
    //CameraX
    implementation "androidx.camera:camera-core:1.1.0-beta01"
    implementation "androidx.camera:camera-camera2:1.1.0-beta01"
    implementation "androidx.camera:camera-lifecycle:1.1.0-beta01"
    implementation "androidx.camera:camera-view:1.1.0-beta01"
    implementation "androidx.camera:camera-extensions:1.1.0-beta01"

If you have any solution to work around, please let me know.

**Comment by maxim-nosov-cko** [comment] 2022-07-11 09:30
Hey @thinhnguyen18.

Thank you for the update.
I will try to reproduce the issue.

Could you please exclude `geetest_captcha_android_v1.7.1.1_20220308` from dependencies and try to build without it?
So we could be sure that there is no conflict with it, as I'll not be able to check exactly this library on my side.

**Comment by thinhnguyen18** [comment] 2022-07-11 10:17
Hi @maxim-nosov-cko ,
I try to build without `geetest_captcha_android_v1.7.1.1_20220308` but the build fail still remains.

However, I try to rename your dimens key from your demo and wrap a new `aar` file and it worked. But it is just the work around solution.
>  <dimen name="checkout_button_height">40dp</dimen>
    <dimen name="checkout_button_width">100dp</dimen>

**Comment by patrick-hoban-cko** [comment] 2022-07-13 09:27
Hey @thinhnguyen18 we're planning to release a fix for this with our new version of the SDK, but this change won't happen for a couple of months. 

We'd recommend not changing the source code and creating a new `aar`.

**Comment by maxim-nosov-cko** [comment] 2022-12-21 16:46
Hey @thinhnguyen18

Please take a look at the latest Frames SDK 4.0.0+ and please know if it's still an issue.

**Closed** 2023-01-04 12:15 UTC
